

```{r, message=FALSE}
#data_list from clean_data.rmd
packages.used=c("text2vec", "knitr")
packages.needed=setdiff(packages.used, 
                        intersect(installed.packages()[,1], 
                                  packages.used))

if(length(packages.needed)>0){
  install.packages(packages.needed, dependencies = TRUE)
}
library(knitr)
source("../lib/paper1_func.R")
source("../lib/cd_cluster_func.R")
source("../lib/cd_cluster.R")
```

```{r}
start.time <- Sys.time()
table1<-matrix(0, nrow = 2, ncol = 2)
accuracy1<-c()
ratio<-c()
result1<-list()
for(k in 1:length(data_list)){
  result1<-paper1_indiv(k)
  table1<-table1+result1[[1]]
  accuracy1[k]<-result1[[2]]$accuracy
  ratio[k]<-result1[[3]]
}
eval1<-performance_statistics(table1)
plot(ratio, accuracy1, main = "Number of Paper per Author for Each Dataset vs Accuracy")
end.time <- Sys.time()
time1 <- end.time - start.time
table1
```
```{r}
start.time <- Sys.time()
table2<-matrix(0, nrow = 2, ncol = 2)
accuracy2<-c()
result2<-list()
for(k in 1:length(data_list)){
  result2<-combinecluster(cd_cluster(k))
  table2<-table2+result2[[1]]
  accuracy2[k]<-result2[[2]]$accuracy
}
eval2<-performance_statistics(table2)
plot(ratio, accuracy2, main = "Number of Paper per Author for Each Dataset vs Accuracy")
end.time <- Sys.time()
time2 <- end.time - start.time
table2
```
```{r}
start.time <- Sys.time()
table3<-matrix(0, nrow = 2, ncol = 2)
accuracy3<-c()
result3<-list()
for(k in 1:length(data_list)){
  result3<-deletecluster(cd_cluster(k))
  table3<-table3+result3[[1]]
  accuracy3[k]<-result3[[2]]$accuracy
}
eval3<-performance_statistics(table3)
plot(ratio, accuracy3, main = "Number of Paper per Author for Each Dataset vs Accuracy")
end.time <- Sys.time()
time3 <- end.time - start.time
table3
```
```{r}
compare_df <- data.frame(method=c("Individual Cluster","Combine Cluster","Delete Cluster"),
                         precision=c(eval1$precision, eval2$precision, eval3$precision),
                         recall=c(eval1$recall, eval2$recall, eval3$recall),
                         f1=c(eval1$f1, eval2$f1, eval3$f1),
                         accuracy=c(eval1$accuracy, eval2$accuracy, eval3$accuracy),
                         time=c(time1,time2, time3))
result_table<-kable(compare_df,caption="Comparision of performance for three clustering methods",digits = 2)
result_table
```

```{r}
save(eval1, eval2, eval3, ratio, accuracy1, accuracy2, accuracy3, time1, time2, time3, result_table, table1, table2, table3, file = "../output/paper1.RData")
```
